# Generated by Django 3.1.6 on 2021-02-04 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_contact_number',
            field=models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(message='Please enter valid phone number', regex='^0([1-6][0-9]{8,10}|7[0-9]{9})$')]),
        ),
    ]
