# Generated by Django 3.1.6 on 2021-02-08 17:08

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210204_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_contact_number',
            field=models.CharField(default='', max_length=60, validators=[django.core.validators.RegexValidator(message='Please enter valid phone number', regex='^0([1-6][0-9]{8,10}|7[0-9]{9})$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_counrty',
            field=django_countries.fields.CountryField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_street_address1',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_town',
            field=models.CharField(default='', max_length=40),
        ),
    ]
