# Generated by Django 3.1.6 on 2021-02-08 17:11

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210208_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_counrty',
            field=django_countries.fields.CountryField(default='Counrty*', max_length=2),
        ),
    ]
