# Generated by Django 3.1.6 on 2021-02-08 17:54

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210208_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_counrty',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
