# Generated by Django 3.1.6 on 2021-03-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210325_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
