"""
WSGI config for amy_hollis_photography project.

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/howto/deployment/wsgi/
"""

import os

from django.core.wsgi import get_wsgi_application

# line too long, generated by Django on project creation
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'amy_hollis_photography.settings')

application = get_wsgi_application()
