# Generated by Django 3.1.6 on 2021-03-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_id',
            field=models.CharField(default='placeholder_id', max_length=50),
            preserve_default=False,
        ),
    ]
