# Generated by Django 3.1.6 on 2021-03-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20210324_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(default='placeholder', max_length=50),
            preserve_default=False,
        ),
    ]
