# Generated by Django 3.1.6 on 2021-03-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_orderitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size_len',
            field=models.CharField(max_length=25),
        ),
    ]
