# Generated by Django 3.1.6 on 2021-03-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20210324_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_id',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(max_length=20000),
        ),
    ]
