# Generated by Django 3.1.6 on 2021-03-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('quantity', models.IntegerField()),
                ('size_len', models.CharField(max_length=30)),
                ('finish_img', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=6)),
            ],
        ),
    ]
