# Generated by Django 3.1.6 on 2021-02-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='finish',
            options={'verbose_name_plural': 'Finishes'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='sizes',
            options={'verbose_name_plural': 'Sizes'},
        ),
        migrations.AddField(
            model_name='categories',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
