# Generated by Django 3.1.6 on 2021-03-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210209_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
