# Generated by Django 3.1.6 on 2021-03-19 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210319_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='date',
            field=models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(message='Please enter YYYY format', regex='[1-2][0-9][0-9][0-9]')]),
        ),
    ]
