# Generated by Django 3.1.6 on 2021-03-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210319_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finish',
            name='finish',
            field=models.CharField(max_length=25),
        ),
    ]
