# Generated by Django 3.1.6 on 2021-03-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210322_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='finish',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
